version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=clearDV.settings
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: 