# Generated by Django 5.2.1 on 2025-05-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.CharField(max_length=50, verbose_name='Время выполнения')),
                ('area', models.CharField(max_length=50, verbose_name='Площадь в м²')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='services/', verbose_name='Фото услуги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на отзыв')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('photo', models.ImageField(upload_to='reviews/', verbose_name='Фото автора')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('area', models.CharField(max_length=50, verbose_name='Площадь')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
