# Generated by Django 5.2.1 on 2025-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_service_review_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Внешний ID'),
            preserve_default=False,
        ),
    ]
