# Generated by Django 5.2.1 on 2025-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_review_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Главный экран'), ('about', 'О нас'), ('services', 'Услуги'), ('portfolio', 'Портфолио'), ('reviews', 'Отзывы'), ('clients', 'Клиенты'), ('contact', 'Контакты')], max_length=50, unique=True, verbose_name='Секция')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать секцию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Содержимое секции',
                'verbose_name_plural': 'Содержимое секций',
                'ordering': ['section'],
            },
        ),
    ]
